---
# Nginx installation and configuration tasks

- name: Install Nginx packages
  apt:
    name: "{{ nginx_packages }}"
    state: present
    update_cache: yes
  become: true

- name: Start Nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Create Nginx configuration directory
  file:
    path: /etc/nginx/sites-available
    state: directory
    mode: '0755'
  become: true

- name: Create Nginx sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled
    state: directory
    mode: '0755'
  become: true

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Create MMC Nginx configuration
  template:
    src: mmc-nginx.conf.j2
    dest: /etc/nginx/sites-available/mmc
    mode: '0644'
  become: true

- name: Enable MMC site
  file:
    src: /etc/nginx/sites-available/mmc
    dest: /etc/nginx/sites-enabled/mmc
    state: link
  become: true

- name: Test Nginx configuration
  command: nginx -t
  become: true

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
  become: true

- name: Verify Nginx status
  service:
    name: nginx
    state: started
  become: true