---
# Rust toolchain installation tasks

- name: Install Rust toolchain for deploy user
  become_user: "{{ rust_user }}"
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source ~/.cargo/env
    echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc
  args:
    creates: "{{ rust_home }}/.cargo/bin/rustc"

- name: Verify Rust installation
  become_user: "{{ rust_user }}"
  command: "{{ rust_home }}/.cargo/bin/rustc --version"
  register: rust_version

- name: Verify Cargo installation
  become_user: "{{ rust_user }}"
  command: "{{ rust_home }}/.cargo/bin/cargo --version"
  register: cargo_version

- name: Display Rust versions
  debug:
    msg:
      - "Rust: {{ rust_version.stdout }}"
      - "Cargo: {{ cargo_version.stdout }}"