---
# Docker installation and configuration tasks

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  become: true

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Add deploy user to docker group
  user:
    name: "{{ deploy_user }}"
    groups: docker
    append: yes
  become: true

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: true

- name: Verify Docker installation
  command: docker --version
  register: docker_version
  become: true

- name: Verify Docker Compose installation
  command: docker-compose --version
  register: docker_compose_version
  become: true

- name: Display Docker versions
  debug:
    msg:
      - "Docker: {{ docker_version.stdout }}"
      - "Docker Compose: {{ docker_compose_version.stdout }}"