---
# MMC Application deployment tasks

- name: Clone MMC repository
  become_user: "{{ deploy_user }}"
  git:
    repo: "{{ mmc_repo }}"
    dest: "{{ mmc_dir }}"
    version: "{{ mmc_branch }}"
    force: yes

- name: Set ownership of MMC directory
  file:
    path: "{{ mmc_dir }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    recurse: yes
  become: true

- name: Build Rust backend services
  become_user: "{{ deploy_user }}"
  shell: |
    cd {{ mmc_dir }}/backend/web-gateway
    source ~/.cargo/env
    cargo build --release
  args:
    creates: "{{ mmc_dir }}/backend/web-gateway/target/release/web-gateway"

- name: Build Matrix Bridge
  become_user: "{{ deploy_user }}"
  shell: |
    cd {{ mmc_dir }}/backend/matrix-bridge
    source ~/.cargo/env
    cargo build --release
  args:
    creates: "{{ mmc_dir }}/backend/matrix-bridge/target/release/matrix-bridge"

- name: Install frontend dependencies
  become_user: "{{ deploy_user }}"
  shell: |
    cd {{ mmc_dir }}/frontend
    npm install
  args:
    creates: "{{ mmc_dir }}/frontend/node_modules"

- name: Build frontend
  become_user: "{{ deploy_user }}"
  shell: |
    cd {{ mmc_dir }}/frontend
    npm run build
  args:
    creates: "{{ mmc_dir }}/frontend/dist"

- name: Create systemd service for Web Gateway
  template:
    src: web-gateway.service.j2
    dest: /etc/systemd/system/mmc-web-gateway.service
    mode: '0644'
  become: true

- name: Create systemd service for Matrix Bridge
  template:
    src: matrix-bridge.service.j2
    dest: /etc/systemd/system/mmc-matrix-bridge.service
    mode: '0644'
  become: true

- name: Create systemd service for Frontend
  template:
    src: frontend.service.j2
    dest: /etc/systemd/system/mmc-frontend.service
    mode: '0644'
  become: true

- name: Enable and start Web Gateway service
  service:
    name: mmc-web-gateway
    enabled: yes
    state: started
  become: true

- name: Enable and start Matrix Bridge service
  service:
    name: mmc-matrix-bridge
    enabled: yes
    state: started
  become: true

- name: Enable and start Frontend service
  service:
    name: mmc-frontend
    enabled: yes
    state: started
  become: true

- name: Wait for services to start
  pause:
    seconds: 10

- name: Verify Web Gateway is running
  uri:
    url: "http://localhost:{{ web_gateway_port }}/health"
    method: GET
    status_code: 200
  register: web_gateway_check
  retries: 5
  delay: 2
  until: web_gateway_check.status == 200

- name: Verify Frontend is running
  uri:
    url: "http://localhost:{{ frontend_port }}"
    method: GET
    status_code: 200
  register: frontend_check
  retries: 5
  delay: 2
  until: frontend_check.status == 200